version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  app:
    build : .
    ports:
      - 8000:8000
    depends_on:
      - mongo
volumes:
  mongo:
